todoapp/urls.py
from django.urls import path
from . import views
app_name = 'todoapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('todo/', views.todoappView, name='todo'),
    path('addTodoItem/',views.addTodoView), 
    path('deleteTodoItem/<int:i>/', views.deleteTodoView), 
] 

todoproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todoapp.urls',)),
    path('', include('userauth.urls',)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

userauth/urls.py
from django.urls import path
from . import views
app_name = 'userauth'
urlpatterns = [
    path('login/', views.t_login, name='login'),
    path('signup/',views.t_sign_up, name='signup'),
    path('logout/',views.logoutUser,name='logout')
] 

todoapp/models.py
from django.db import models


# Create your models here.
class TodoListItem(models.Model):
    user = models.CharField(max_length=100)
    content = models.TextField() 
    priority = models.TextField() 
    date1=models.DateField(auto_now_add=True)

userauth/models.py
from django.db import models

# Create your models here.

todoapp/views.py
from django.shortcuts import render
from .models import TodoListItem 
from django.http import HttpResponseRedirect 

from django.contrib.auth.decorators import login_required
# Create your views here.
def index(request):
    return render(request, 'index.html')


@login_required(login_url='/login')
def todoappView(request):
    
    user_email = request.user.email
    # all_todo_items = TodoListItem.objects.all()
    all_todo_items = TodoListItem.objects.filter(user=user_email)
    return render(request, 'todolist.html',  {'all_items':all_todo_items})

@login_required(login_url='/login')
def addTodoView(request):
    # x = request.POST.get('todotext')
    user_email = request.user.email
    new_item = TodoListItem()
    new_item.user = user_email
    new_item.content = request.POST.get('content')
    new_item.date1 = request.POST.get('date1')
    new_item.priority = request.POST.get('priority')
    new_item.save()
    return HttpResponseRedirect('/todo/') 
    
@login_required(login_url='/login')
def deleteTodoView(request, i):
    y = TodoListItem.objects.get(id= i)
    y.delete()
    return HttpResponseRedirect('/todo/') 

userauth/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
# from .models import users

from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User

from django.http import HttpResponse
from django.forms import inlineformset_factory
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth import authenticate, login, logout

from django.contrib import messages

from django.contrib.auth.decorators import login_required

from .models import *
# from .forms import CreateUserForm
# Create your views here.


def t_sign_up(request):
    if request.user.is_authenticated:
        return redirect('/todo')
    else:
        if request.method == 'POST':
            if request.POST['nPassword1'].strip() == request.POST['nPassword2'].strip():
                user = User(password=make_password(request.POST['nPassword1'].strip()),
                            username=request.POST['nEmail'],
                            email=request.POST['nEmail'])
                user.save()
                # userdetails = f_users(user_name=user.username, email=user.email,
                #                           mobile_number=request.POST['nPhone'], user_id=user)
                # userdetails = f_users(user_Id=user, user_Email=user.email)
                # userdetails.save()
                return redirect('userauth:login')
            else:
                context = {
                    'msg': 'Error in the inputs given, kindly make sure that you are using proper details to create user'
                }
                return render(request, 'signup.html', context)
        context = {
            'msg': ''
        }
        return render(request, 'signup.html', context)


def t_login(request):
	if request.user.is_authenticated:
		return redirect('/todo')
	else:
		if request.method == 'POST':
			Email = request.POST.get('email_address')
			password =request.POST.get('password')
			user = authenticate(request, username=Email, password=password)

			if user is not None:
				login(request, user)
				if 'next' in request.POST:
					return redirect(request.POST.get('next'))
				# elif user.is_staff == 1:
				# 	return redirect('main:admin_dashboard')
				else:
					return redirect('todoapp:todo')
			else:
				print('Login is not success')
				# messages.info(request, 'Username OR password is incorrect')

		context = {}
		return render(request, 'login.html', context)

def logoutUser(request):
	logout(request)
	return redirect('/login')

templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <title>Document</title>
</head>

<body style="background-image: linear-gradient(rgb(90, 236, 236),rgb(90, 197, 236));">
    <div class="container">
        <div class="row">
            <img src="{% static 'img/todo1.png' %}" alt="" class="img-fluid mx-auto d-block float-center r-50" style="width: 600px; height:200px; margin-top: 50px;">
        </div>
        <div class="card text-center" style="margin-top: 80px; background-color: rgb(165, 235, 235); margin-bottom: 133px; margin-left: 300px; margin-right: 300px;">
            <div class="card-header">
                <h6>WELCOME</h6>
            </div>
            <div class="card-body">
                <a href="{% url 'todoapp:todo' %}" class="btn btn-primary" style="background-color: black;">Start!</a>
            </div>
            <div class="card-footer text-muted">
                Make life easier by creating ToDo List
            </div>
        </div>
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>

</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>Document</title>
</head>

<body>


    <section class="vh-100" style="background-color:rgb(90, 197, 236);">
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-lg-12 col-xl-11">
                    <div class="card text-black" style="border-radius: 25px;background-color: rgb(90, 236, 236);">
                        <div class="card-body p-md-5">
                            <div class=" row justify-content-center ">
                                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1 ">

                                    <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4 ">Login</p>

                                    <form class="mx-1 mx-md-4 " method="post ">
                                        {% csrf_token %}
                                        <div class="d-flex flex-row align-items-center mb-4 ">
                                            <i class="fas fa-envelope fa-lg me-3 fa-fw "></i>
                                            <div class="form-outline flex-fill mb-0 ">
                                                <label class="form-label " for="email_address ">Your Email</label>
                                                <input type="email " name="email_address " id="email_address " class="form-control " />
                                            </div>
                                        </div>

                                        <div class="d-flex flex-row align-items-center mb-4 ">
                                            <i class="fas fa-lock fa-lg me-3 fa-fw "></i>
                                            <div class="form-outline flex-fill mb-0 ">
                                                <label class="form-label " for="password ">Password</label>
                                                <input type="password " id="password " name="password " class="form-control " />
                                            </div>
                                        </div>


                                        <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4 ">
                                            <button type="submit " class="btn btn-primary btn-lg " style="background-color: black;">Login</button>
                                        </div>

                                    </form>

                                    <h6 class=" text-center mt-1 " style="color: var(--light-black); ">Dont have an account <a href="{% url 'userauth:signup' %} " style="color:black ; "><u>Sign Up</u></a> now!</h6>

                                </div>
                                <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2 ">

                                    <img src="{% static 'img/todo1.png' %} " class="img-fluid " alt="Sample image ">

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js " integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4 " crossorigin="anonymous "></script>
</body>

</html>

templates/signup.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>Document</title>
</head>

<body>

    <section class="vh-100" style="background-color:rgb(90, 197, 236); ">
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-lg-12 col-xl-11">
                    <div class="card text-black" style="border-radius: 25px; background-color: rgb(90, 236, 236); ">
                        <div class="card-body p-md-5">
                            <div class="row justify-content-center ">
                                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1 ">

                                    <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4 ">Sign up</p>

                                    <form class="mx-1 mx-md-4 " method="post ">
                                        {% csrf_token %}
                                        <div class="d-flex flex-row align-items-center mb-4 ">
                                            <i class="fas fa-user fa-lg me-3 fa-fw "></i>
                                            <div class="form-outline flex-fill mb-0 ">
                                                <label class="form-label " for="nUsername ">User Name</label>
                                                <input type="text " name="nUsername " id="nUsername " class="form-control " />
                                            </div>
                                        </div>

                                        <div class="d-flex flex-row align-items-center mb-4 ">
                                            <i class="fas fa-envelope fa-lg me-3 fa-fw "></i>
                                            <div class="form-outline flex-fill mb-0 ">
                                                <label class="form-label " for="nEmail ">Your Email</label>
                                                <input type="email " name="nEmail " id="nEmail " class="form-control " />
                                            </div>
                                        </div>

                                        <div class="d-flex flex-row align-items-center mb-4 ">
                                            <i class="fas fa-lock fa-lg me-3 fa-fw "></i>
                                            <div class="form-outline flex-fill mb-0 ">
                                                <label class="form-label " for="nPassword1 ">Password</label>
                                                <input type="password " name="nPassword1 " id="nPassword1 " class="form-control " />
                                            </div>
                                        </div>

                                        <div class="d-flex flex-row align-items-center mb-4 ">
                                            <i class="fas fa-key fa-lg me-3 fa-fw "></i>
                                            <div class="form-outline flex-fill mb-0 ">
                                                <label class="form-label " for="nPassword2 ">Repeat your password</label>
                                                <input type="password " name="nPassword2 " id="nPassword2 " class="form-control " />
                                            </div>
                                        </div>


                                        <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4 ">
                                            <button type="submit " class="btn btn-primary btn-lg " style="background-color: black;">Register</button>
                                        </div>

                                    </form>

                                    <h6 class="text-center mt-1 " style="color: var(--light-black); ">Already have an account? <a href="{% url 'userauth:login' %} " style="color:black ; "><u>Login</u></a> now!</h6>


                                </div>
                                <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2 ">

                                    <img src="{% static 'img/todo1.png' %} " class=" img-fluid " alt="Sample image ">

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js " integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4 " crossorigin="anonymous "></script>
</body>

</html>

templates/todolist.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <title>Document</title>
</head>

<body style="background-image: linear-gradient(rgb(90, 236, 236),rgb(90, 197, 236));">

    <div class="container">
        <div class="userrr" style="margin-top: 20px; margin-left:900px">
            <p>User: {{request.user}}</p>
            <a href="/logout" class="btn btn-primary" style="background-color: black;">Logout</a>
        </div>
        <div class="row" style="margin-top: 10px; margin-left:25%; margin-right: 20%;  margin-bottom: 500px;">

            <div class="col">

                <div class="row ">
                    <form class="form-inline " action="/addTodoItem/ " method="post ">
                        {% csrf_token %}

                        <div class="row ">
                            <div class="col-8 ">
                                <div class="form-group mx-sm-3 mb-2 ">
                                    <label for="content " class="sr-only "></label>
                                    <input type="text " class="form-control " name="content " placeholder="Research ">
                                </div>
                            </div>
                            <div class="col-3 " style="margin-top: 25px; ">
                                <button type="submit " class="btn btn-primary mb-2 " style="background-color: black; ">Add Todo</button>
                            </div>

                            <div class=" col-8 ">
                                <div class="form-group mx-sm-3 mb-2 ">
                                    <form action="/action_page.php ">
                                        <label for="priority ">Importance</label>
                                        <select name="priority " id="priority ">
                                      <option value="Urgent ">Urgent</option>
                                      <option value="General ">General</option>
                                      <option value="Occasional ">Occasional</option>
                                    </select>
                                        <br><br>
                                    </form>



                                </div>

                    </form>

                    </div>
                    {% for i in all_items %}
                    <div class="row ">
                        <div class="col-1 "></div>
                        <div class="col-6 ">
                            <div class="card text-white bg-dark mb-3 ">
                                <div class="card-body ">
                                    {{i.priority}}
                                </div>
                                <div class="card-body ">
                                    {{i.content}}
                                </div>
                                <div class="card-body ">
                                    {{i.date1}}
                                </div>
                            </div>
                        </div>

                        <div class="col-2 ">
                            <form action="/deleteTodoItem/{{i.id}}/ " method="post ">
                                {% csrf_token %}
                                <button type="submit " class="btn btn-primary " style="background-color: black; margin-top: 10px; ">
                            <svg xmlns="http://www.w3.org/2000/svg " width="16 " height="16 " fill="currentColor " class="bi bi-trash " viewBox="0 0 16 16 ">
                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z "/>
                            <path fill-rule="evenodd " d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0
                                    1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z "/>
                          </svg></i>
                        </button>
                            </form>
                        </div>
                        <div class="col-3 "></div>
                    </div>
                    {% endfor %}
                    </div>
                </div>



            </div>

            <!-- JavaScript Bundle with Popper -->
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js " integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3 " crossorigin="anonymous "></script>
</body>

</html>